### ISSUE TITLE
Executables with `other-modules` end up with incorrect paths

### ISSUE THREAD

**Issue by ocharles** [Avi-D-coder/implicit-hie#17]
I have:

```cabal
executable analyse-quoting
  ...
  other-modules:
    CircuitHub.Quoting.Analysis.AssemblyPricing.Picofactory2
    CircuitHub.Quoting.Analysis.CompetitorQuote
    CircuitHub.Quoting.Analysis.FinalOffers
    CircuitHub.Quoting.Analysis.QuoteParameters
    CircuitHub.Quoting.Analysis.Report
    CircuitHub.Quoting.Analysis.Sample
```

But when I run `gen-hie` I get:

```yaml
    - path: "./quoting/exe-analyse-quoting/Main.hs"
      component: "quoting:exe:analyse-quoting"

    - path: "./quoting/exe-analyse-quoting/CircuitHub.Quoting.Analysis.AssemblyPricing.Picofactory2.hs"
      component: "quoting:exe:analyse-quoting"

    - path: "./quoting/exe-analyse-quoting/CircuitHub.Quoting.Analysis.CompetitorQuote.hs"
      component: "quoting:exe:analyse-quoting"

    - path: "./quoting/exe-analyse-quoting/CircuitHub.Quoting.Analysis.FinalOffers.hs"
      component: "quoting:exe:analyse-quoting"

    - path: "./quoting/exe-analyse-quoting/CircuitHub.Quoting.Analysis.QuoteParameters.hs"
      component: "quoting:exe:analyse-quoting"

    - path: "./quoting/exe-analyse-quoting/CircuitHub.Quoting.Analysis.Report.hs"
      component: "quoting:exe:analyse-quoting"

    - path: "./quoting/exe-analyse-quoting/CircuitHub.Quoting.Analysis.Sample.hs"
      component: "quoting:exe:analyse-quoting"
```

Which is wrong - these files don't exist.
