### ISSUE TITLE
Not clear how to install or use

### ISSUE THREAD

**Issue by JivanRoquet** [Avi-D-coder/implicit-hie#25]
Hello,

I've installed `implicit-hie` by adding the following in `stack.yaml`:

```yaml
extra-deps:
  - git: https://github.com/Avi-D-coder/implicit-hie # implicit-hie
    commit: fc1d3329148ea6616cd42d1919c5385a1a577af2
```

and in `project.cabal`:

```cabal
executable descriptions
  build-depends:       ...,
                       ...,
                       implicit-hie,
                       base >= 4.7 && < 5
```

and running `stack build`.

When I type `gen-hie` into a terminal, I get a `command not found: gen-hie` error.

Is there something specific more to do? How can we declare where the executable should go?
