### ISSUE TITLE
Generates too many executables

### ISSUE THREAD

**Issue by domenkozar** [Avi-D-coder/implicit-hie#27]
Given

```cabal
...

executable cachix-server
  import:         defaults
  main-is:        Main.hs
  other-modules:
    CollectMetrics
    DeleteNars
    ExpireTrials
    GarbageCollection
    GenElm
    Migrate
    SyncGitHub

  ...
```

It generates

```yaml
cradle:
  stack:
    - path: "./exe/cachix-server/Main.hs"
      component: "cachix-server:exe:cachix-server"

    - path: "./exe/cachix-server/CollectMetrics.hs"
      component: "cachix-server:exe:cachix-server"

    - path: "./exe/cachix-server/DeleteNars.hs"
      component: "cachix-server:exe:cachix-server"

    - path: "./exe/cachix-server/ExpireTrials.hs"
      component: "cachix-server:exe:cachix-server"

    - path: "./exe/cachix-server/GarbageCollection.hs"
      component: "cachix-server:exe:cachix-server"

    - path: "./exe/cachix-server/GenElm.hs"
      component: "cachix-server:exe:cachix-server"

    - path: "./exe/cachix-server/Migrate.hs"
      component: "cachix-server:exe:cachix-server"

    - path: "./exe/cachix-server/SyncGitHub.hs"
      component: "cachix-server:exe:cachix-server"
```
