### ISSUE TITLE
Support curly braces

### ISSUE THREAD

**Issue by anka-213** [Avi-D-coder/implicit-hie#28]
Cabal files apparently allows writing curly braces around blocks, which confuses implicit-hie. For example, this file: https://github.com/ivan-m/graphviz/blob/42dbb6312d7edf789d7055079de7b4fa099a4acc/graphviz.cabal#L59

```
Library {

-- ...
```

will generate a `hie.yaml` file like this

```
cradle:
  cabal:
    - path: "./"
      component: "graphviz:lib:{"

# ...
```

instead of the expected

```
cradle:
  cabal:
    - path: "./"
      component: "lib:graphviz"

# ...
```
