### ISSUE TITLE
Issues with cabal.project pointing to current directory

### ISSUE THREAD

**Issue by georgefst** [Avi-D-coder/implicit-hie#32]
My `cabal.project` has:

```
packages:
    ./.
    ../reanimate-svg
```

`implict-hie` produces:

```
cradle:
  cabal:
    - path: "../reanimate-svg/src"
      component: "lib:reanimate-svg"

    - path: "../reanimate-svg/test"
      component: "reanimate-svg:test:w3c-spec"
```

When I'd expect:
```
cradle:
  cabal:
    - path: "./app/Main.hs"
      component: "svgone:exe:svgone"

    - path: "./src"
      component: "lib:svgone"

    - path: "../reanimate-svg/src"
      component: "lib:reanimate-svg"

    - path: "../reanimate-svg/test"
      component: "reanimate-svg:test:w3c-spec"
```

Which is actually what I get if I change `./.` to `.`. But the latter isn't actually valid syntax - cabal gives:
```
cabal: Error parsing project file
/Users/gthomas/personal/svgone/cabal.project:1:
Parse of field 'packages' failed.
```
