### ISSUE TITLE
Implicit hie fails to generate the main lib component due to package description

### ISSUE THREAD

**Issue by jneira** [Avi-D-coder/implicit-hie#39]
* Reported by @IvanMalison in irc
* Commit removing the description: https://github.com/taffybar/taffybar/commit/257a620162e3ababe5012ac7a24d8a3ea1238afe
* Description:

```
  Taffybar is a gtk+3 (through gi-gtk) based desktop information bar, intended
  primarily for use with XMonad, though it can also function alongside other EWMH
  compliant window managers. It is similar in spirit to xmobar, but it differs in
  that it gives up some simplicity for a reasonable helping of eye candy. 
```

* hie.yaml generated with the description (it misses the existing library component)

```
cradle:
  cabal:
    - path: "./app/Main.hs"
      component: "taffybar:exe:taffybar"

    - path: "./app/Paths_taffybar.hs"
      component: "taffybar:exe:taffybar"
```

I dont see at a first look what part of the decription is triggering the bug
